name: CI
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        redis_ruby: ["~> 4.6"]
        redis_server: ["4", "5", "6.2"]
        ruby: ["2.7", "3.0"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Set up Redis 4
        uses: supercharge/redis-github-action@1.2.0
        with:
          redis-version: ${{ matrix.redis_server }}

      - run: gem uninstall redis
      - run: gem install redis -v '${{ matrix.redis_ruby }}'

      - name: Run tests
        run: bin/test
